import { Tool, Notification, AuditEntry, Task, Document, CalibrationEvent, User } from '@/types';
import { addDays, subDays, format, addMonths } from 'date-fns';

const today = new Date();
const fmt = (d: Date) => format(d, 'yyyy-MM-dd');

export const MOCK_TOOLS: Tool[] = [
  // OVERDUE tools
  {
    id: 'HAL-QM-001', toolName: 'Digital Vernier Caliper 150mm', category: 'Dimensional Measurement',
    serialNumber: 'DEMO-VC-001', manufacturer: 'Mitutoyo Corp (Demo)', modelNumber: 'CD-6"CSX',
    department: 'Quality Metrology', storageLocation: 'Metrology Rack A1',
    responsiblePerson: 'Rajesh Kumar', range: '0-150mm', accuracy: '±0.02mm',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 380)),
    expiryDate: fmt(subDays(today, 15)), nextCalibrationDate: fmt(addMonths(today, 11)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-001',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 90)),
    nextInspectionDate: fmt(addDays(today, 90)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', remarks: 'Priority calibration tool',
    riskLevel: 'HIGH', createdAt: '2023-01-15T09:00:00', updatedAt: fmt(subDays(today, 15)),
  },
  {
    id: 'HAL-QM-002', toolName: 'Outside Micrometer 0-25mm', category: 'Dimensional Measurement',
    serialNumber: 'DEMO-OM-002', manufacturer: 'Mitutoyo Corp (Demo)', modelNumber: 'MDC-25MX',
    department: 'Quality Metrology', storageLocation: 'Metrology Rack A1',
    responsiblePerson: 'Priya Sharma', range: '0-25mm', accuracy: '±0.001mm',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 370)),
    expiryDate: fmt(subDays(today, 8)), nextCalibrationDate: fmt(addMonths(today, 11)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-002',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 60)),
    nextInspectionDate: fmt(addDays(today, 120)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'HIGH', createdAt: '2023-01-15T09:00:00', updatedAt: fmt(subDays(today, 8)),
  },
  {
    id: 'HAL-QM-003', toolName: 'Pressure Gauge 0-100 Bar', category: 'Pressure & Vacuum',
    serialNumber: 'DEMO-PG-003', manufacturer: 'Wika Demo Instruments', modelNumber: 'A-10',
    department: 'Hydraulics & Pneumatics', storageLocation: 'Lab Bench 1',
    responsiblePerson: 'Anil Verma', range: '0-100 Bar', accuracy: '±0.5%',
    calibrationFrequencyMonths: 6, calibrationDate: fmt(subDays(today, 195)),
    expiryDate: fmt(subDays(today, 12)), nextCalibrationDate: fmt(addMonths(today, 5)),
    calibrationAgency: 'In-House Calibration Lab', certificateNumber: 'DEMO-CERT-2024-003',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 50)),
    nextInspectionDate: fmt(addDays(today, 130)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-03-10T09:00:00', updatedAt: fmt(subDays(today, 12)),
  },
  {
    id: 'HAL-QM-004', toolName: 'Digital Multimeter', category: 'Electrical & Electronic',
    serialNumber: 'DEMO-DM-004', manufacturer: 'Fluke Demo Corp', modelNumber: '87V',
    department: 'Electrical Systems', storageLocation: 'Metrology Rack B1',
    responsiblePerson: 'Sunita Nair', range: 'DC/AC 1000V', accuracy: '±0.05%',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 375)),
    expiryDate: fmt(subDays(today, 10)), nextCalibrationDate: fmt(addMonths(today, 11)),
    calibrationAgency: 'ISO/IEC 17025 Lab - Sigma Calibration', certificateNumber: 'DEMO-CERT-2024-004',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 80)),
    nextInspectionDate: fmt(addDays(today, 100)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-02-20T09:00:00', updatedAt: fmt(subDays(today, 10)),
  },
  {
    id: 'HAL-QM-005', toolName: 'Torque Wrench 20-200 Nm', category: 'Force & Torque',
    serialNumber: 'DEMO-TW-005', manufacturer: 'Norbar Demo Tools', modelNumber: 'Pro200',
    department: 'Production Engineering', storageLocation: 'Toolroom Cabinet T1',
    responsiblePerson: 'Vikram Singh', range: '20-200 Nm', accuracy: '±4%',
    calibrationFrequencyMonths: 6, calibrationDate: fmt(subDays(today, 192)),
    expiryDate: fmt(subDays(today, 5)), nextCalibrationDate: fmt(addMonths(today, 5)),
    calibrationAgency: 'NABL Accredited Lab - Precision Standards', certificateNumber: 'DEMO-CERT-2024-005',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 45)),
    nextInspectionDate: fmt(addDays(today, 135)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'HIGH', createdAt: '2023-04-01T09:00:00', updatedAt: fmt(subDays(today, 5)),
  },
  {
    id: 'HAL-QM-006', toolName: 'Surface Roughness Tester', category: 'Surface Finish',
    serialNumber: 'DEMO-SR-006', manufacturer: 'Mitutoyo Corp (Demo)', modelNumber: 'SJ-210',
    department: 'Quality Metrology', storageLocation: 'Metrology Rack A2',
    responsiblePerson: 'Deepa Menon', range: 'Ra 0.05-16µm', accuracy: '±10%',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 368)),
    expiryDate: fmt(subDays(today, 3)), nextCalibrationDate: fmt(addMonths(today, 11)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-006',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 100)),
    nextInspectionDate: fmt(addDays(today, 80)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-01-20T09:00:00', updatedAt: fmt(subDays(today, 3)),
  },
  // DUE TODAY
  {
    id: 'HAL-QM-007', toolName: 'Height Gauge Digital 300mm', category: 'Dimensional Measurement',
    serialNumber: 'DEMO-HG-007', manufacturer: 'Mitutoyo Corp (Demo)', modelNumber: '192-130',
    department: 'Quality Metrology', storageLocation: 'Metrology Rack A3',
    responsiblePerson: 'Rajesh Kumar', range: '0-300mm', accuracy: '±0.03mm',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 365)),
    expiryDate: fmt(today), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-007',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 70)),
    nextInspectionDate: fmt(addDays(today, 110)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'HIGH', createdAt: '2023-01-15T09:00:00', updatedAt: fmt(today),
  },
  {
    id: 'HAL-QM-008', toolName: 'Optical Comparator 10x', category: 'Optical',
    serialNumber: 'DEMO-OC-008', manufacturer: 'Nikon Demo Optics', modelNumber: 'V-12B',
    department: 'Quality Metrology', storageLocation: 'Calibration Room C1',
    responsiblePerson: 'Priya Sharma', range: '250mm stage', accuracy: '±0.005mm',
    calibrationFrequencyMonths: 6, calibrationDate: fmt(subDays(today, 180)),
    expiryDate: fmt(today), nextCalibrationDate: fmt(addMonths(today, 6)),
    calibrationAgency: 'NPL Traceable Lab - Delta Instruments', certificateNumber: 'DEMO-CERT-2024-008',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 30)),
    nextInspectionDate: fmt(addDays(today, 150)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-06-01T09:00:00', updatedAt: fmt(today),
  },
  {
    id: 'HAL-QM-009', toolName: 'Temperature Calibrator Dry Block', category: 'Temperature',
    serialNumber: 'DEMO-TC-009', manufacturer: 'Fluke Demo Corp', modelNumber: '9103',
    department: 'Materials Laboratory', storageLocation: 'Lab Bench 2',
    responsiblePerson: 'Ramesh Patel', range: '-25°C to 140°C', accuracy: '±0.15°C',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 365)),
    expiryDate: fmt(today), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'ISO/IEC 17025 Lab - Sigma Calibration', certificateNumber: 'DEMO-CERT-2024-009',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 120)),
    nextInspectionDate: fmt(addDays(today, 60)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-01-25T09:00:00', updatedAt: fmt(today),
  },
  // DUE TOMORROW
  {
    id: 'HAL-QM-010', toolName: 'CMM Touch Probe', category: 'Dimensional Measurement',
    serialNumber: 'DEMO-CP-010', manufacturer: 'Renishaw Demo', modelNumber: 'TP20',
    department: 'Quality Metrology', storageLocation: 'Calibration Room C1',
    responsiblePerson: 'Kavitha Rajan', range: 'XYZ 500mm', accuracy: '±0.003mm',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 364)),
    expiryDate: fmt(addDays(today, 1)), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-010',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 45)),
    nextInspectionDate: fmt(addDays(today, 135)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'HIGH', createdAt: '2023-01-30T09:00:00', updatedAt: fmt(today),
  },
  {
    id: 'HAL-QM-011', toolName: 'Pneumatic Gauge Air Plug', category: 'Air Gauging',
    serialNumber: 'DEMO-AG-011', manufacturer: 'Federal Demo Products', modelNumber: 'AG-25',
    department: 'Production Engineering', storageLocation: 'Production Floor Cabinet',
    responsiblePerson: 'Vikram Singh', range: '25mm bore', accuracy: '±0.001mm',
    calibrationFrequencyMonths: 6, calibrationDate: fmt(subDays(today, 179)),
    expiryDate: fmt(addDays(today, 1)), nextCalibrationDate: fmt(addMonths(today, 6)),
    calibrationAgency: 'In-House Calibration Lab', certificateNumber: 'DEMO-CERT-2024-011',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 60)),
    nextInspectionDate: fmt(addDays(today, 120)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-06-10T09:00:00', updatedAt: fmt(today),
  },
  {
    id: 'HAL-QM-012', toolName: 'Force Gauge Digital 500N', category: 'Force & Torque',
    serialNumber: 'DEMO-FG-012', manufacturer: 'Shimpo Demo Instruments', modelNumber: 'FG-5000',
    department: 'Structural Testing', storageLocation: 'Lab Bench 3',
    responsiblePerson: 'Suresh Babu', range: '0-500N', accuracy: '±0.5%',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 364)),
    expiryDate: fmt(addDays(today, 1)), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NABL Accredited Lab - Precision Standards', certificateNumber: 'DEMO-CERT-2024-012',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 90)),
    nextInspectionDate: fmt(addDays(today, 90)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-02-05T09:00:00', updatedAt: fmt(today),
  },
  {
    id: 'HAL-QM-013', toolName: 'Hardness Tester Rockwell', category: 'Hardness Testing',
    serialNumber: 'DEMO-HT-013', manufacturer: 'Wilson Demo Hardness', modelNumber: 'B2000',
    department: 'Materials Laboratory', storageLocation: 'Lab Bench 2',
    responsiblePerson: 'Anitha Krishnan', range: 'HRA/HRB/HRC', accuracy: '±0.5 HR',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 363)),
    expiryDate: fmt(addDays(today, 1)), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NPL Traceable Lab - Delta Instruments', certificateNumber: 'DEMO-CERT-2024-013',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 75)),
    nextInspectionDate: fmt(addDays(today, 105)), inspectionStatus: 'PASSED',
    toolStatus: 'ACTIVE', riskLevel: 'LOW', createdAt: '2023-02-10T09:00:00', updatedAt: fmt(today),
  },
  // DUE WITHIN 7 DAYS
  ...Array.from({ length: 12 }, (_, i) => ({
    id: `HAL-QM-0${14 + i}`,
    toolName: [
      'Vernier Caliper 200mm', 'Depth Micrometer 0-25mm', 'Dial Test Indicator',
      'Gauge Block Set', 'Ultrasonic Thickness Gauge', 'Vibration Analyzer',
      'Oscilloscope 100MHz', 'LCR Meter', 'Thermocouple Calibrator',
      'Deadweight Tester', 'Angle Plate Reference', 'Autocollimator',
    ][i],
    category: ['Dimensional Measurement', 'Dimensional Measurement', 'Dimensional Measurement',
      'Length Standards', 'NDT Equipment', 'Vibration Analysis',
      'Electrical & Electronic', 'Electrical & Electronic', 'Temperature',
      'Pressure & Vacuum', 'Angle & Geometry', 'Optical'][i],
    serialNumber: `DEMO-${['VC', 'DM', 'DI', 'GB', 'UT', 'VA', 'OS', 'LM', 'TC', 'DW', 'AP', 'AC'][i]}-0${14 + i}`,
    manufacturer: ['Mitutoyo Corp (Demo)', 'Mitutoyo Corp (Demo)', 'Starrett Demo', 'Mitutoyo Corp (Demo)',
      'Olympus Demo', 'Brüel & Kjær Demo', 'Tektronix Demo', 'Keysight Demo',
      'Fluke Demo Corp', 'Ashcroft Demo', 'Mitutoyo Corp (Demo)', 'Taylor Hobson Demo'][i],
    modelNumber: `MODEL-${14 + i}`,
    department: ['Quality Metrology', 'Production Engineering', 'Quality Metrology', 'Central Standards Room',
      'NDT Division', 'Structural Testing', 'Electrical Systems', 'Electrical Systems',
      'Materials Laboratory', 'Hydraulics & Pneumatics', 'Quality Metrology', 'Quality Metrology'][i],
    storageLocation: ['Metrology Rack A2', 'Production Floor Cabinet', 'Metrology Rack A3', 'Standards Room Safe',
      'NDT Store', 'Lab Bench 3', 'Metrology Rack B2', 'Metrology Rack B2',
      'Lab Bench 2', 'Lab Bench 1', 'Metrology Rack A4', 'Calibration Room C2'][i],
    responsiblePerson: ['Priya Sharma', 'Vikram Singh', 'Rajesh Kumar', 'Mohan Das',
      'Suresh Babu', 'Deepa Menon', 'Sunita Nair', 'Anitha Krishnan',
      'Ramesh Patel', 'Anil Verma', 'Kavitha Rajan', 'Lakshmi Iyer'][i],
    range: 'Various', accuracy: 'Per Spec',
    calibrationFrequencyMonths: [12, 12, 12, 12, 12, 12, 12, 12, 6, 12, 24, 12][i],
    calibrationDate: fmt(subDays(today, [360, 358, 356, 354, 352, 350, 348, 346, 174, 362, 353, 355][i])),
    expiryDate: fmt(addDays(today, [2, 3, 4, 5, 6, 7, 2, 4, 3, 6, 5, 7][i])),
    nextCalibrationDate: fmt(addMonths(today, [12, 12, 12, 12, 12, 12, 12, 12, 6, 12, 24, 12][i])),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology',
    certificateNumber: `DEMO-CERT-2024-0${14 + i}`,
    lastCalibrationResult: 'PASSED',
    inspectionDate: fmt(subDays(today, 60 + i * 5)),
    nextInspectionDate: fmt(addDays(today, 120 + i * 3)),
    inspectionStatus: 'PASSED' as const,
    toolStatus: 'ACTIVE' as const,
    riskLevel: ['MEDIUM', 'LOW', 'HIGH', 'LOW', 'MEDIUM', 'HIGH', 'MEDIUM', 'LOW', 'MEDIUM', 'LOW', 'LOW', 'MEDIUM'][i] as 'LOW' | 'MEDIUM' | 'HIGH',
    createdAt: '2023-02-15T09:00:00',
    updatedAt: fmt(subDays(today, 5)),
  })),
  // DUE WITHIN 30 DAYS
  ...Array.from({ length: 20 }, (_, i) => ({
    id: `HAL-QM-0${26 + i}`,
    toolName: [
      'Ring Gauge Go/No-Go', 'Plug Gauge Set', 'Feeler Gauge Set', 'Thread Gauge Metric',
      'Signal Generator', 'Power Analyzer', 'Sound Level Meter', 'Vacuum Gauge',
      'Flow Meter Turbine', 'Torque Tester 5 Nm', 'Anemometer Digital', 'Clinometer',
      'Profile Projector', 'Spectrometer Portable', 'Optical Flat Set',
      'Precision Level', 'Roundness Tester', 'Form Tester', 'Gear Measurement System',
      'Coordinate Measuring Arm',
    ][i],
    category: 'Dimensional Measurement',
    serialNumber: `DEMO-EQ-0${26 + i}`,
    manufacturer: 'Various Demo Manufacturers',
    modelNumber: `MODEL-0${26 + i}`,
    department: ['Quality Metrology', 'Production Engineering', 'Production Engineering', 'Quality Metrology',
      'Electrical Systems', 'Electrical Systems', 'NDT Division', 'Hydraulics & Pneumatics',
      'Hydraulics & Pneumatics', 'Production Engineering', 'NDT Division', 'Quality Metrology',
      'Quality Metrology', 'Materials Laboratory', 'Central Standards Room',
      'Central Standards Room', 'Quality Metrology', 'Quality Metrology', 'Production Engineering', 'Quality Metrology'][i],
    storageLocation: 'Metrology Rack A4',
    responsiblePerson: ['Rajesh Kumar', 'Priya Sharma', 'Anil Verma', 'Sunita Nair',
      'Vikram Singh', 'Deepa Menon', 'Ramesh Patel', 'Kavitha Rajan',
      'Suresh Babu', 'Anitha Krishnan', 'Mohan Das', 'Lakshmi Iyer',
      'Rajesh Kumar', 'Priya Sharma', 'Anil Verma', 'Sunita Nair',
      'Vikram Singh', 'Deepa Menon', 'Ramesh Patel', 'Kavitha Rajan'][i],
    range: 'Various', accuracy: 'Per Spec',
    calibrationFrequencyMonths: 12,
    calibrationDate: fmt(subDays(today, 345 + i * 2)),
    expiryDate: fmt(addDays(today, 8 + i * 1.1 | 0)),
    nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'In-House Calibration Lab',
    certificateNumber: `DEMO-CERT-2024-0${26 + i}`,
    lastCalibrationResult: 'PASSED',
    inspectionDate: fmt(subDays(today, 90 + i * 3)),
    nextInspectionDate: fmt(addDays(today, 90 + i * 2)),
    inspectionStatus: (i % 5 === 0 ? 'DUE' : 'PASSED') as 'PASSED' | 'DUE',
    toolStatus: 'ACTIVE' as const,
    riskLevel: 'LOW' as const,
    createdAt: '2023-03-01T09:00:00',
    updatedAt: fmt(subDays(today, 10)),
  })),
  // VALID tools
  ...Array.from({ length: 25 }, (_, i) => ({
    id: `HAL-QM-0${46 + i}`,
    toolName: [
      'Bore Gauge 50-160mm', 'Inside Micrometer 50-75mm', 'Snap Gauge 35mm',
      'Dial Bore Gauge', 'Laser Tracker', 'CMM Zeiss Contura', 'Profile Scanner',
      'Video Measuring System', 'Hardness Tester Vickers', 'Impact Test Machine',
      'Tensile Testing Machine', 'Fatigue Testing Machine', 'Ultrasonic Flaw Detector',
      'Eddy Current Tester', 'Magnetic Particle Tester', 'Radiographic Film Viewer',
      'Electronic Balance 0.1mg', 'Electronic Balance 0.01g', 'Dead Weight Set 10kg',
      'Reference Thermometer', 'Humidity Chamber', 'Salt Spray Chamber',
      'Thermal Shock Chamber', 'Environmental Chamber', 'Spectrum Analyzer',
    ][i],
    category: 'Dimensional Measurement',
    serialNumber: `DEMO-VL-0${46 + i}`,
    manufacturer: 'Various Demo Manufacturers',
    modelNumber: `MODEL-0${46 + i}`,
    department: 'Quality Metrology',
    storageLocation: 'Metrology Rack B1',
    responsiblePerson: ['Rajesh Kumar', 'Priya Sharma', 'Anil Verma', 'Sunita Nair', 'Vikram Singh'][i % 5],
    range: 'Various', accuracy: 'Per Spec',
    calibrationFrequencyMonths: 12,
    calibrationDate: fmt(subDays(today, 100 + i * 5)),
    expiryDate: fmt(addDays(today, 31 + i * 5)),
    nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology',
    certificateNumber: `DEMO-CERT-2024-0${46 + i}`,
    lastCalibrationResult: 'PASSED',
    inspectionDate: fmt(subDays(today, 30 + i * 3)),
    nextInspectionDate: fmt(addDays(today, 150 + i * 2)),
    inspectionStatus: 'PASSED' as const,
    toolStatus: 'ACTIVE' as const,
    riskLevel: 'LOW' as const,
    createdAt: '2023-04-01T09:00:00',
    updatedAt: fmt(subDays(today, 20)),
  })),
  // UNDER CALIBRATION
  {
    id: 'HAL-QM-071', toolName: 'CMM Hexagon Global Advantage', category: 'Dimensional Measurement',
    serialNumber: 'DEMO-CMM-071', manufacturer: 'Hexagon Demo AB', modelNumber: 'Global Advantage',
    department: 'Quality Metrology', storageLocation: 'Calibration Room C1',
    responsiblePerson: 'Rajesh Kumar', range: 'XYZ 700mm', accuracy: '±0.002mm',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 365)),
    expiryDate: fmt(addDays(today, 30)), nextCalibrationDate: fmt(addMonths(today, 12)),
    calibrationAgency: 'NABL Accredited Lab - Alpha Metrology', certificateNumber: 'DEMO-CERT-2024-071',
    lastCalibrationResult: 'PASSED', inspectionDate: fmt(subDays(today, 30)),
    nextInspectionDate: fmt(addDays(today, 150)), inspectionStatus: 'PASSED',
    toolStatus: 'UNDER_CALIBRATION', riskLevel: 'HIGH', createdAt: '2023-01-10T09:00:00', updatedAt: fmt(today),
  },
  // MISSING DATA (for data quality demo)
  {
    id: 'HAL-QM-072', toolName: 'Angle Decoder', category: 'Angle & Geometry',
    serialNumber: 'DEMO-AD-072', manufacturer: 'Heidenhain Demo', modelNumber: 'ROD 800',
    department: 'Quality Metrology', storageLocation: '',
    responsiblePerson: '', range: '360°', accuracy: '±1"',
    calibrationFrequencyMonths: 12, calibrationDate: fmt(subDays(today, 200)),
    expiryDate: '', nextCalibrationDate: '',
    calibrationAgency: '', certificateNumber: '',
    lastCalibrationResult: '', inspectionDate: '',
    nextInspectionDate: '', inspectionStatus: 'PENDING',
    toolStatus: 'ACTIVE', riskLevel: 'MEDIUM', createdAt: '2023-05-01T09:00:00', updatedAt: fmt(subDays(today, 50)),
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n001', type: 'CRITICAL',
    title: 'Calibration Overdue — HAL-QM-001',
    message: 'Digital Vernier Caliper 150mm (HAL-QM-001) calibration is OVERDUE by 15 days. Responsible: Rajesh Kumar. Location: Metrology Rack A1. Immediate action required.',
    toolId: 'HAL-QM-001', toolName: 'Digital Vernier Caliper 150mm',
    timestamp: fmt(subDays(today, 1)) + 'T08:00:00', read: false, escalationLevel: 3,
  },
  {
    id: 'n002', type: 'CRITICAL',
    title: 'Calibration Overdue — HAL-QM-002',
    message: 'Outside Micrometer 0-25mm (HAL-QM-002) calibration is OVERDUE by 8 days. Responsible: Priya Sharma. Escalated to Quality Manager.',
    toolId: 'HAL-QM-002', toolName: 'Outside Micrometer 0-25mm',
    timestamp: fmt(subDays(today, 1)) + 'T08:01:00', read: false, escalationLevel: 2,
  },
  {
    id: 'n003', type: 'DUE_TODAY',
    title: 'Calibration Due Today — HAL-QM-007',
    message: 'Height Gauge Digital 300mm (HAL-QM-007) calibration expires TODAY. Responsible: Rajesh Kumar. Please initiate calibration immediately.',
    toolId: 'HAL-QM-007', toolName: 'Height Gauge Digital 300mm',
    timestamp: fmt(today) + 'T07:00:00', read: false,
  },
  {
    id: 'n004', type: 'DUE_TODAY',
    title: 'Calibration Due Today — HAL-QM-008',
    message: 'Optical Comparator 10x (HAL-QM-008) calibration expires TODAY. Responsible: Priya Sharma.',
    toolId: 'HAL-QM-008', toolName: 'Optical Comparator 10x',
    timestamp: fmt(today) + 'T07:01:00', read: false,
  },
  {
    id: 'n005', type: 'DUE_TOMORROW',
    title: 'Calibration Due Tomorrow — HAL-QM-010',
    message: 'CMM Touch Probe (HAL-QM-010) calibration expires TOMORROW. Responsible: Kavitha Rajan. Please initiate calibration action.',
    toolId: 'HAL-QM-010', toolName: 'CMM Touch Probe',
    timestamp: fmt(today) + 'T06:00:00', read: false,
  },
  {
    id: 'n006', type: 'ESCALATION',
    title: 'Escalation — HAL-QM-005 Overdue Day 3',
    message: 'ESCALATION: Torque Wrench 20-200 Nm (HAL-QM-005) overdue by 5 days. No action recorded. Escalated to Quality Manager and Department Head.',
    toolId: 'HAL-QM-005', toolName: 'Torque Wrench 20-200 Nm',
    timestamp: fmt(subDays(today, 2)) + 'T08:30:00', read: true, escalationLevel: 3,
  },
  {
    id: 'n007', type: 'SYSTEM',
    title: 'Daily Calibration Check Completed',
    message: 'Automated daily calibration status check completed. 6 overdue, 3 due today, 4 due tomorrow. Report generated.',
    timestamp: fmt(today) + 'T06:30:00', read: true,
  },
  {
    id: 'n008', type: 'UPCOMING',
    title: '12 Tools Due in 7 Days',
    message: '12 instruments have calibration expiring within the next 7 days. Review the Deadline Monitor.',
    timestamp: fmt(today) + 'T06:31:00', read: false,
  },
  {
    id: 'n009', type: 'SYSTEM',
    title: 'Data Import Completed',
    message: 'Excel import completed successfully. 72 records imported. 3 duplicates skipped.',
    timestamp: fmt(subDays(today, 3)) + 'T14:20:00', read: true,
  },
  {
    id: 'n010', type: 'IMPORT_ERROR',
    title: 'Import Warning: Missing Expiry Dates',
    message: '5 records in the last import had missing expiry dates and were not imported. Review Data Quality for details.',
    timestamp: fmt(subDays(today, 3)) + 'T14:21:00', read: true,
  },
];

export const MOCK_AUDIT_LOG: AuditEntry[] = [
  {
    id: 'a001', timestamp: fmt(today) + 'T09:15:22', userId: 'u001', userName: 'Admin User',
    action: 'Updated calibration expiry date', toolId: 'HAL-QM-007', toolName: 'Height Gauge Digital 300mm',
    field: 'Expiry Date', oldValue: fmt(subDays(today, 1)), newValue: fmt(today),
    ipAddress: '192.168.1.10', module: 'Tool Register',
  },
  {
    id: 'a002', timestamp: fmt(today) + 'T08:45:10', userId: 'u002', userName: 'Rajesh Kumar',
    action: 'Marked tool as Under Calibration', toolId: 'HAL-QM-071', toolName: 'CMM Hexagon Global Advantage',
    field: 'Tool Status', oldValue: 'ACTIVE', newValue: 'UNDER_CALIBRATION',
    ipAddress: '192.168.1.15', module: 'Tool Register',
  },
  {
    id: 'a003', timestamp: fmt(today) + 'T07:30:00', userId: 'u000', userName: 'System',
    action: 'Generated calibration deadline reminders', toolId: undefined,
    module: 'Notification Engine',
  },
  {
    id: 'a004', timestamp: fmt(subDays(today, 1)) + 'T16:20:44', userId: 'u003', userName: 'Priya Sharma',
    action: 'Uploaded calibration certificate', toolId: 'HAL-QM-002', toolName: 'Outside Micrometer 0-25mm',
    field: 'Certificate', oldValue: 'None', newValue: 'DEMO-CERT-2024-002-REV1.pdf',
    ipAddress: '192.168.1.22', module: 'Documents',
  },
  {
    id: 'a005', timestamp: fmt(subDays(today, 2)) + 'T14:10:00', userId: 'u001', userName: 'Admin User',
    action: 'Imported Excel data file', toolId: undefined,
    field: 'Import', oldValue: undefined, newValue: '72 records imported',
    ipAddress: '192.168.1.10', module: 'Data Import',
  },
  {
    id: 'a006', timestamp: fmt(subDays(today, 2)) + 'T11:30:15', userId: 'u004', userName: 'Anil Verma',
    action: 'Updated task status', toolId: 'HAL-QM-003', toolName: 'Pressure Gauge 0-100 Bar',
    field: 'Task Status', oldValue: 'IN_PROGRESS', newValue: 'SENT_FOR_CALIBRATION',
    ipAddress: '192.168.1.30', module: 'Tasks',
  },
  {
    id: 'a007', timestamp: fmt(subDays(today, 3)) + 'T09:00:00', userId: 'u000', userName: 'System',
    action: 'Generated escalation for overdue tool', toolId: 'HAL-QM-005', toolName: 'Torque Wrench 20-200 Nm',
    field: 'Escalation Level', oldValue: '2', newValue: '3',
    module: 'Escalation Engine',
  },
  {
    id: 'a008', timestamp: fmt(subDays(today, 5)) + 'T14:55:30', userId: 'u003', userName: 'Priya Sharma',
    action: 'Edited tool details', toolId: 'HAL-QM-010', toolName: 'CMM Touch Probe',
    field: 'Responsible Person', oldValue: 'Mohan Das', newValue: 'Kavitha Rajan',
    ipAddress: '192.168.1.22', module: 'Tool Register',
  },
  {
    id: 'a009', timestamp: fmt(subDays(today, 7)) + 'T10:20:00', userId: 'u002', userName: 'Rajesh Kumar',
    action: 'Approved calibration record', toolId: 'HAL-QM-020', toolName: 'Oscilloscope 100MHz',
    field: 'Approval', oldValue: 'PENDING', newValue: 'APPROVED',
    ipAddress: '192.168.1.15', module: 'Calibration',
  },
  {
    id: 'a010', timestamp: fmt(subDays(today, 10)) + 'T15:45:00', userId: 'u001', userName: 'Admin User',
    action: 'Added new user', toolId: undefined,
    field: 'User', oldValue: 'None', newValue: 'Anitha Krishnan (TECHNICIAN)',
    ipAddress: '192.168.1.10', module: 'User Management',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 't001', toolId: 'HAL-QM-001', toolName: 'Digital Vernier Caliper 150mm',
    assignedTo: 'Rajesh Kumar', dueDate: fmt(addDays(today, 2)),
    priority: 'CRITICAL', remarks: 'URGENT: Overdue by 15 days. Submit to NABL lab immediately.',
    status: 'PENDING', createdAt: fmt(subDays(today, 15)) + 'T09:00:00', updatedAt: fmt(today) + 'T09:00:00',
    createdBy: 'Admin User',
  },
  {
    id: 't002', toolId: 'HAL-QM-003', toolName: 'Pressure Gauge 0-100 Bar',
    assignedTo: 'Anil Verma', dueDate: fmt(addDays(today, 1)),
    priority: 'CRITICAL', remarks: 'Sent to in-house calibration lab.',
    status: 'SENT_FOR_CALIBRATION', createdAt: fmt(subDays(today, 12)) + 'T10:00:00', updatedAt: fmt(subDays(today, 2)) + 'T14:00:00',
    createdBy: 'Rajesh Kumar',
  },
  {
    id: 't003', toolId: 'HAL-QM-007', toolName: 'Height Gauge Digital 300mm',
    assignedTo: 'Rajesh Kumar', dueDate: fmt(today),
    priority: 'HIGH', remarks: 'Due today. Collect from Rack A3 and submit.',
    status: 'IN_PROGRESS', createdAt: fmt(subDays(today, 3)) + 'T08:00:00', updatedAt: fmt(today) + 'T07:30:00',
    createdBy: 'Admin User',
  },
  {
    id: 't004', toolId: 'HAL-QM-010', toolName: 'CMM Touch Probe',
    assignedTo: 'Kavitha Rajan', dueDate: fmt(addDays(today, 1)),
    priority: 'HIGH', remarks: 'Contact NABL lab for appointment. Due tomorrow.',
    status: 'PENDING', createdAt: fmt(subDays(today, 2)) + 'T09:00:00', updatedAt: fmt(subDays(today, 2)) + 'T09:00:00',
    createdBy: 'Priya Sharma',
  },
  {
    id: 't005', toolId: 'HAL-QM-020', toolName: 'Oscilloscope 100MHz',
    assignedTo: 'Sunita Nair', dueDate: fmt(addDays(today, 5)),
    priority: 'MEDIUM', remarks: 'Schedule with external calibration agency.',
    status: 'IN_PROGRESS', createdAt: fmt(subDays(today, 5)) + 'T09:00:00', updatedAt: fmt(subDays(today, 1)) + 'T11:00:00',
    createdBy: 'Rajesh Kumar',
  },
];

export const MOCK_USERS: User[] = [
  { id: 'u001', name: 'Admin User', email: 'admin@mcms.gov.in', role: 'ADMINISTRATOR', department: 'Quality Metrology', isActive: true, lastLogin: fmt(today) + 'T08:00:00' },
  { id: 'u002', name: 'Rajesh Kumar', email: 'rajesh.kumar@mcms.gov.in', role: 'QUALITY_MANAGER', department: 'Quality Metrology', isActive: true, lastLogin: fmt(today) + 'T08:30:00' },
  { id: 'u003', name: 'Priya Sharma', email: 'priya.sharma@mcms.gov.in', role: 'METROLOGY_ENGINEER', department: 'Quality Metrology', isActive: true, lastLogin: fmt(subDays(today, 1)) + 'T16:00:00' },
  { id: 'u004', name: 'Anil Verma', email: 'anil.verma@mcms.gov.in', role: 'TECHNICIAN', department: 'Production Engineering', isActive: true, lastLogin: fmt(subDays(today, 1)) + 'T14:00:00' },
  { id: 'u005', name: 'Sunita Nair', email: 'sunita.nair@mcms.gov.in', role: 'METROLOGY_ENGINEER', department: 'Electrical Systems', isActive: true, lastLogin: fmt(subDays(today, 2)) + 'T09:00:00' },
  { id: 'u006', name: 'Vikram Singh', email: 'vikram.singh@mcms.gov.in', role: 'TECHNICIAN', department: 'Production Engineering', isActive: true, lastLogin: fmt(subDays(today, 1)) + 'T10:00:00' },
  { id: 'u007', name: 'Deepa Menon', email: 'deepa.menon@mcms.gov.in', role: 'METROLOGY_ENGINEER', department: 'Quality Metrology', isActive: false, lastLogin: fmt(subDays(today, 15)) + 'T09:00:00' },
  { id: 'u008', name: 'Ramesh Patel', email: 'ramesh.patel@mcms.gov.in', role: 'VIEWER', department: 'Materials Laboratory', isActive: true, lastLogin: fmt(subDays(today, 3)) + 'T11:00:00' },
];

export const MOCK_CALIBRATION_HISTORY: CalibrationEvent[] = [
  { id: 'h001', toolId: 'HAL-QM-001', type: 'CALIBRATION', date: fmt(subDays(today, 380)), description: 'Annual calibration completed. All parameters within tolerance.', performedBy: 'Alpha Metrology Lab', result: 'PASSED', certificateRef: 'DEMO-CERT-2023-001' },
  { id: 'h002', toolId: 'HAL-QM-001', type: 'INSPECTION', date: fmt(subDays(today, 90)), description: 'Periodic inspection completed. No physical damage noted.', performedBy: 'Rajesh Kumar', result: 'PASSED' },
  { id: 'h003', toolId: 'HAL-QM-001', type: 'REMINDER', date: fmt(subDays(today, 15)), description: 'Calibration expiry reminder generated by system.', performedBy: 'System' },
  { id: 'h004', toolId: 'HAL-QM-001', type: 'ESCALATION', date: fmt(subDays(today, 12)), description: 'Escalation generated: Day 3 overdue. Notified Rajesh Kumar + Supervisor.', performedBy: 'System' },
  { id: 'h005', toolId: 'HAL-QM-007', type: 'CALIBRATION', date: fmt(subDays(today, 365)), description: 'Annual calibration completed. Reference std traceability maintained.', performedBy: 'Alpha Metrology Lab', result: 'PASSED', certificateRef: 'DEMO-CERT-2024-007' },
  { id: 'h006', toolId: 'HAL-QM-007', type: 'REMINDER', date: fmt(subDays(today, 30)), description: '30-day calibration expiry reminder sent to Rajesh Kumar.', performedBy: 'System' },
  { id: 'h007', toolId: 'HAL-QM-007', type: 'REMINDER', date: fmt(today), description: 'Calibration expires TODAY. Urgent action notification sent.', performedBy: 'System' },
];
